import { Vehicle } from './types';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'car-1',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2023,
    price: 89900,
    mileage: 12500,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800',
    description: 'Une accélération inégalée et un confort absolu. Berline 100 % électrique de 1020 chevaux. État comme neuf, intérieur cuir blanc premium, Autopilot amélioré inclus.',
    transmission: 'Automatique',
    fuel: 'Électrique',
    color: 'Bleu Outremer',
    status: 'available',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'car-2',
    brand: 'Porsche',
    model: '911 Carrera S',
    year: 2022,
    price: 124500,
    mileage: 8200,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    description: 'Le mythe par excellence. Propulsée par un flat-6 biturbo développant 450 ch. Échappement sport, jantes Carrera Classic 20/21 pouces, toit ouvrant vitré, écotaxe payée.',
    transmission: 'Automatique',
    fuel: 'Essence',
    color: 'Gris Quartz',
    status: 'available',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'car-3',
    brand: 'Audi',
    model: 'RS e-tron GT',
    year: 2023,
    price: 112000,
    mileage: 4500,
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=800',
    description: 'L\'art du design électrique par Audi Sport. Transmission intégrale quattro, phares Matrix LED laser, suspension pneumatique adaptative. Autonomie de 480 km WLTP.',
    transmission: 'Automatique',
    fuel: 'Électrique',
    color: 'Noir Mythic',
    status: 'available',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'car-4',
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2021,
    price: 79500,
    mileage: 24000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800',
    description: 'Le coupé ultra-sportif de référence. Moteur 6 cylindres en ligne de 510 ch, boîte de vitesses M de 8 rapports. Intérieur carbone, affichage tête haute, freins M performance.',
    transmission: 'Automatique',
    fuel: 'Essence',
    color: 'Jaune Sao Paulo',
    status: 'available',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'car-5',
    brand: 'Land Rover',
    model: 'Defender 110 V8',
    year: 2022,
    price: 98000,
    mileage: 18500,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=800',
    description: 'La quintessence du tout-terrain de luxe. Motorisation V8 suralimentée de 525 chevaux. Équipements complets baroudeur chic, toit noir contrasté, système audio Meridian Surround.',
    transmission: 'Automatique',
    fuel: 'Essence',
    color: 'Gris Eiger',
    status: 'available',
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'car-6',
    brand: 'Mercedes-Benz',
    model: 'AMG GT C Coupé',
    year: 2020,
    price: 118000,
    mileage: 19800,
    image: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?auto=format&fit=crop&q=80&w=800',
    description: 'Des sensations de course sur route ouverte. V8 biturbo AMG de 4.0L développant 557 ch. Roues arrière directrices, échappement sport commutable, sono haut de gamme.',
    transmission: 'Automatique',
    fuel: 'Essence',
    color: 'Noir Satin',
    status: 'sold',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const AVAILABLE_BRANDS = [
  'Tesla',
  'Porsche',
  'Audi',
  'BMW',
  'Mercedes-Benz',
  'Land Rover',
  'Aston Martin',
  'Ferrari',
  'Lamborghini',
  'Peugeot',
  'Renault',
  'Toyota',
];

export const AVAILABLE_FUELS = ['Essence', 'Diesel', 'Électrique', 'Hybride'];
export const AVAILABLE_TRANSMISSIONS = ['Automatique', 'Manuelle'];
